### ISSUE TITLE
SatelliteDynamics and SatelliteToolbox Compatibility 

### ISSUE THREAD

**Issue by kevin-tracy** [sisl/SatelliteDynamics.jl#8] opened 2020-07-16 23:48 UTC
It looks like you can't have the newest versions of SatelliteDynamics and SatelliteToolbox running together. The two packages are on the following versions:

SatelliteDynamics.jl - v0.4.0
SatelliteToolbox.jl     - v0.7.1

If you try to add these packages, it will downgrade one of them, or it will be unable to run due to dependency issues. It looks like the issues stem from either StaticArrays.jl or SOFA.jl.

**Comment by duncaneddy** [comment] 2020-07-17 14:26
This is likely being caused by how Julia packaging handles package compatibility for pre-1.0 packages like static arrays. See https://julialang.github.io/Pkg.jl/v1/compatibility/#compat-pre-1.0-1 for an explanation.

SatelliteDynamics.jl has a dependency on StaticArrays v0.11 where has SatelliteToolbox.jl has increased their dependency to v0.12.

It is the most technically correct and safest to individually bump the StaticArray dependency on each new release since it is a pre-1.0 package. However, it believe it has been stable for a while so a dependency of `"0.12 - 0"` should be sufficient until it reaches 1.0

**Comment by duncaneddy** [comment] 2020-07-18 16:50
Fixed in https://github.com/sisl/SatelliteDynamics.jl/releases/tag/v0.4.1

Submitted to registry for merging https://github.com/JuliaRegistries/General/pull/18134

**Closed as completed by duncaneddy** 2020-07-18 16:50 UTC
