### ISSUE TITLE
Tutorial example not working

### ISSUE THREAD

**Issue by henry2004y** [sisl/SatelliteDynamics.jl#5] opened 2020-02-02 16:18 UTC
Hi,

The current [examples](https://sisl.github.io/SatelliteDynamics.jl/latest/tutorials/orbit_propagation_example/) in the tutorials does not work on my Mac. 

```julia
julia> # Propagate the orbit
       t, epc, eci = simulate(orb, epcf, timestep=1, dtmax=1)
ERROR: UndefVarError: simulate not defined
```

Also, the `sim!` function is also not defined.

**Comment by duncaneddy** [comment] 2020-02-02 16:56
Hi,

I'll take a look to see where the regression happened to break the examples. If it's a quick fix I'll try to have it out shortly. If it takes longer it may take me a little bit to get to.

**Comment by duncaneddy** [comment] 2020-02-02 17:05
It would also help to know what package version you are using where the error occurs.

**Comment by duncaneddy** [comment] 2020-02-02 18:04
Ok, so a recent refactor broke the documentation build process, as well as making the documentation generally out of date. I've fixed the issues but need to cut an updated release of the  package to get the examples to work directly out of the box for the current release.

The examples will work but you'll need to install from the master branch until I get an updated release with the refactor out. This should do it for now`] add https://github.com/sisl/SatelliteDynamics.jl/`

Going to close this issue for now as it looks like it's resolved. Let me know if it isn't.

**Closed as completed by duncaneddy** 2020-02-02 18:04 UTC
